### ISSUE TITLE
Frontend feedback #3

### ISSUE THREAD

**Issue by tenokami** [arc53/DocsGPT#157]
- [x] 1. Set all paddings of the text in messages to 0.9rem (on mobile too)
- [x] 2. Like/dislike buttons should have the outline color the same as the color inside (like in figma)
- [x] 3. The scrollbar width is too small. Its impossible to click and drag ot it with mouse
- [x] 4. The arrow in the documentation selection dropdown should look down when closed (up if opened)

Mobile version of the like/dislike buttons:

- [x] 1. Buttons should behave the same way as on desktop except that they are always visible in neutral state since u can't hover the message.  After one of them is clicked, we can keep the other one visisble so the user can change their choice

- [ ] #415
![image](https://github.com/arc53/DocsGPT/assets/17906039/6fa6a7e5-1c04-4843-a626-7807ea23491f)

**Comment by Thayalan21** [comment]
Bro do u mind if i ask an error in token issue?

openai.error.InvalidRequestError: This model's maximum context length is 4097 tokens. However, your messages resulted in 5107 tokens. Please reduce the length of the messages.

**Comment by Thayalan21** [comment]
![image](https://user-images.githubusercontent.com/104500045/228734251-5930c31b-4954-47c7-ae44-7734de3193ee.png)
The error above shows up after this question is asked .Other than that its working fine

**Comment by abdulriiyaz** [comment]
I'm implementing the dropdown expansion from [mui](https://mui.com/material-ui/react-text-field/), from optional enhancement.

- [X] 1. Set all paddings of the text in messages to 0.9rem (on mobile too)

 - [X] 2. Like/dislike buttons should have the outline color the same as the color inside (like in figma)
- [X]  3. The scrollbar width is too small. Its impossible to click and drag ot it with mouse
- [X]  4. The arrow in the documentation selection dropdown should look down when closed (up if opened)
Mobile version of the like/dislike buttons:

- [X]  1. Buttons should behave the same way as on desktop except that they are always visible in neutral state since u can't hover the message. After one of them is clicked, we can keep the other one visisble so the user can change their choice

(Optional enhancement)
- [ ]  Copy the design for the dropdown options from here (when the dropdown is expanded) https://mui.com/material-ui/react-text-field/

**Comment by outlivo** [comment]
Can this be assigned to me?

**Comment by dartpain** [comment]
Yes @outlivo

**Comment by tenokami** [comment]
Hello. I've updated the last list item.

Duplicating it:

- [ ] Update the UI for dropdown list for Source documentation selection to match the style of the menu for profile 
![image](https://github.com/arc53/DocsGPT/assets/17906039/6fa6a7e5-1c04-4843-a626-7807ea23491f)

Figma:
https://www.figma.com/file/OXLtrl1EAy885to6S69554/DocsGPT?type=design&node-id=0%3A1&mode=design&t=dl0y8pTiva7YoU6z-1
