### ISSUE TITLE
Consider switching FAISS to a faster Vector DB.

### ISSUE THREAD

**Issue by Bnjoroge1** [arc53/DocsGPT#165]
Infernce takes super long and after doing a bunch of profiling tests, it seems that FAISS is bottlenecking the similarity search. I think a POC w Weaviate or Pinecone or Qdrant would be faster.

**Comment by dartpain** [comment]
it takes long due to multiple calls being made in the background, we could benefit from parallelising them. 
As of vector store its local and did try to compare speed of vector search in both
Time for FAISS:
<img width="146" alt="image" src="https://user-images.githubusercontent.com/15183589/224304986-384e8c34-de1c-45d2-bf60-c2f680228e7c.png">

Time for Pinecone:
<img width="298" alt="image" src="https://user-images.githubusercontent.com/15183589/224305030-3d6263a8-c413-409a-8173-6b5e865a025a.png">

Although once we create user uploads i think we will have to use one of the proper db vector search methods with them
