### ISSUE TITLE
inference for long pdf

### ISSUE THREAD

**Issue by liulfy** [arc53/DocsGPT#229]
I find that for a pdf with more than 4 pages, DocsGPT can only recognize information on subsequent  pages. How to deal with this situation?

**Comment by fjljlzy** [comment]
This issue could be quite reasonable. ChatGPT only use last 4096 tokens as input, so it seems to be only recognize information on subsequent pages.

**Comment by larinam** [comment]
In the best case, it should split documents to index those in parts. Need to check the code.

**Comment by psociety** [comment]
@liulfy were you able to find any workaround? I've tried other solutions and they're all crap :(

**Comment by dartpain** [comment]
The best solution is to introduce some metadata that helps you differentiate and understand where each chunk belongs.
we have a metadata function already that captures filename, but that may not be enough in many cases, things like title can help a lot. Maybe writing a short guide in wiki will help

**Comment by psociety** [comment]
@dartpain regarding documentation, i'm a bit confused because the steps on the wiki for document training (https://github.com/arc53/DocsGPT/wiki/How-to-train-on-other-documentation) has nothing to do with the current process (just uploading the pdf).
If we run the training using those steps will it make DocGPT work for large pdfs?
