### ISSUE TITLE
🐛 Bug Report: 

### ISSUE THREAD

**Issue by tenokami** [arc53/DocsGPT#422]
### 📜 Description

Add placeholder text "Type your message here..." to the input field

### 👟 Reproduction steps

1. Go to https://docsgpt.arc53.com/
2. Look at the input field which doesn't have a placeholder
3. Compare to [figma](https://www.figma.com/file/OXLtrl1EAy885to6S69554/DocsGPT?type=design&node-id=1%3A677&mode=design&t=tMBoGNoGdeHF8dmI-1) design which has a placeholder

### 👍 Expected behavior

Should contain a placeholder: "Type your message here..."
![image](https://github.com/arc53/DocsGPT/assets/17906039/d2af4d1b-59cc-4904-804a-fef2584aebc7)

### 👎 Actual Behavior with Screenshots

No visible placeholder

![image](https://github.com/arc53/DocsGPT/assets/17906039/be82dd33-8e24-4bc5-b229-a61da79fc31a)

### 💻 Operating system

Windows

### 🤖 What development environment are you experiencing this bug on?

Docker

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🔗 Are you willing to submit PR?

None

### 🧑‍⚖️ Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by QuantuM410** [comment]
Hey I would like to work on this issue! Can you please assign it?

**Comment by QuantuM410** [comment]
> I would like to contribute to this issue. Is anybody working with it?

yep :hand:

**Comment by QuantuM410** [comment]
Hey! I have been working on this #422 issue in docsGPT. I have to basically just add a placeholder here. As I can see this is in a div instead of an input tag hence cant use ```placeholder="Type your message here..."``` directly
If we want to continue using div then there can be css written to create a placeholder attribute for the div and solve this issue :
```
[contentEditable]:empty::before {
  content: attr(placeholder);
  color: #9ca3af;
  opacity: 1;
}
```
The result will be like in the given recording. So can I hit a PR with the changes or try implementing it with input tag instead

Before :
![Screenshot from 2023-10-05 09-35-34](https://github.com/arc53/DocsGPT/assets/85943021/4d4d5087-bde2-4370-8648-ab61a7e51dee)

After :

https://github.com/arc53/DocsGPT/assets/85943021/87fb85da-e4b0-4902-a4ea-d097a76334b3

**Comment by Vivek-04022001** [comment]
Is there any thing to contribute ?

**Comment by dartpain** [comment]
Check out open issues, and you can always connect more llms or vectorstores to the app. Check out application/ folder
