### ISSUE TITLE
Add license link to readme.md 

### ISSUE THREAD

**Issue by barkhaaroraa** [arc53/DocsGPT#505]
I saw that the license hasn’t been linked on the readme file 
![IMG_2216](https://github.com/arc53/DocsGPT/assets/115429121/ea16d3dc-7a3e-4103-becd-0b3c60fabc78)

![IMG_2215](https://github.com/arc53/DocsGPT/assets/115429121/e5cff926-4866-4e68-95d8-ae8ccf30e24e)

**Comment by sanketmp** [comment]
can I take this?

**Comment by shivam200446** [comment]
Hey, I want to work on it! assign me

**Comment by beKoool** [comment]
Hi guys! I would like to work on this. Can you assign it to me? 👋

**Comment by dartpain** [comment]
Assigned to @sanketmp as he was the first one. Thank you for your enthusiasm @shivam200446  and @beKoool

**Comment by beKoool** [comment]
No problem sir 🔥🙏

**Comment by barkhaaroraa** [comment]
Hi @dartpain since I was the one who raised the issue and saw the bug shouldn’t I be the one assigned?

**Comment by dartpain** [comment]
Sorry @barkhaaroraa thats fair

**Comment by sanketmp** [comment]
to be fair, the one who raises the issue needs to mention whether they want to resolve it or not. 
But it's okay, this is not race. Maintainers, you can close my PR. 👍
Cheers.✌

**Comment by dartpain** [comment]
Ahhh its a bit hard to decide where the issue should go sometimes, I honestly suggest to use templates as it asks user to mention if they are willing to work on a PR. Sorry if it didnt meet anyones expectations.

Also I usually go through my notification to make sure everything is actioned. And i think the issue was already closed.
